name: simple_linter_user
description: linter user
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  simple_linter:
    git:
      url: git@github.com:hisaichi5518/dart-linting.git
      path: example
      ref: fix-example

dev_dependencies:
  test: ^1.17.0
  lints: ^1.0.1