name: linting_example
description: linting example
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  linting: ^1.0.2
  linting_example_plugin_loader:
    path: tools/analyzer_plugin

dev_dependencies:
  test: ^1.17.0
  lints: ^1.0.1

executables:
  linter: