name: linting_cli_example
description: linting cli example
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  linting:
    path: ../

dev_dependencies:
  test: ^1.17.0
  lints: ^1.0.1
