name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
template: |
  $CHANGES
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: minor