name: Linting
packages:
  - packages/**
  - "*"

ide:
  # https://github.com/invertase/melos/issues/9
  intellij: true
  vscode: false

scripts:
  analyze:
    run: melos exec -c 1 -- "dart analyze . --fatal-infos"
    description: Run dart analyzer in a specific package.

  test:
    description: Run tests in a specific package.
    run: melos exec --concurrency=1 -- "dart pub get && dart pub run test --reporter expanded"
    select-package:
      dir-exists:
        - "test/"
    # This tells Melos tests to ignore env variables passed to tests from `melos run test`
    # as they could change the behaviour of how tests filter packages.
    env:
      MELOS_TEST: "true"

  format: dart format -o write .
