name: linting
description: linting is a framework for creating custom linters using the analyzer_plugin or cli.
version: 1.0.0+1
repository: https://github.com/hisaichi5518/dart-linting/

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  analyzer: ^2.7.0
  analyzer_plugin: ^0.8.0
  freezed_annotation: ^0.14.3

dev_dependencies:
  test: ^1.17.0
  lints: ^1.0.1
  build_runner: ^2.1.2
  freezed: ^0.14.5
  mocktail: ^0.2.0
