name: linting_example_plugin_loader
description: This pubspec determines the version of the analyzer plugin to load.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  linting: ^1.0.0

dev_dependencies:
  lints: ^1.0.1