name: validate all packages
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: stable
      - run: ./.github/workflows/scripts/install-tools.sh
      - run: flutter pub get
      - run: flutter analyze .

  format:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: stable
      - run: ./.github/workflows/scripts/install-tools.sh
      - name: "Format"
        run: |
          dart format -o write .
          ./.github/workflows/scripts/validate-formatting.sh


  test_on_linux:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: stable
      - run: ./.github/workflows/scripts/install-tools.sh
      - run: dart test
