name: validate all packages
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: stable
      - run: ./.github/workflows/scripts/install-tools.sh
      - run: melos run analyze

  format:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: stable
      - run: ./.github/workflows/scripts/install-tools.sh
      - run: melos run format

  test_linux:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: stable
      - run: ./.github/workflows/scripts/install-tools.sh
      - run: melos run test